PINECONE_API_KEY = "pcsk_6u1koX_Jidan1AmBK8YVJC6ABfmMpSbX15Kn2gDbBiz2Ti3qEbJqtFepAd6AeYVi8mhWz7"
PINECONE_ENV = "us-east-1"
GROQ_API_KEY = "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"
LANGSMITH_TRACING = true
LANGSMITH_API_KEY = "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"
